/*!
 * questions.js — 16 型人格测试题库
 * --------------------------------------------------------------
 * 设计说明：
 *   - 数据结构按需求文档定义
 *   - direction = +1 表示"完全同意"贡献 +2 到正向极（E/N/T/P/A）
 *   - direction = -1 表示"完全同意"贡献 +2 到负向极（I/S/F/J/T）
 *   - weight 统一 1.0，未来可按题目区分度调整
 *   - 题目全部原创，不抄袭任何现有 MBTI 网站
 *   - 中文口语化、贴近现代生活；英文自然地道
 *
 * 三套题：
 *   - quick28      : q001–q028（28 题，免费）
 *   - standard93   : q029–q121（93 题，付费）
 *   - pro144 新增   : q122–q172（51 题；含 30 道 AT + 21 道深度补充）
 *   pro144 实际呈现 = standard93 的 93 题 + 上述 51 题 = 144 题
 *
 * 维度题量：
 *   quick28        EI 7 / SN 7 / TF 7 / JP 7
 *   standard93     EI 21 / SN 26 / TF 24 / JP 22
 *   pro144 增量     AT 30 / EI+5 / SN+5 / TF+6 / JP+5
 */

const _QUESTIONS_FLAT = [
  /* ============= quick28：EI（7 题，5 正 2 反） ============= */
  { id: 'q001', setCode: 'quick28', dimension: 'EI', direction: +1, weight: 1.0,
    text: { zh: '周末我更想约朋友聚会，而不是一个人待着。', en: "On weekends I'd rather meet up with friends than spend time alone." } },
  { id: 'q002', setCode: 'quick28', dimension: 'EI', direction: +1, weight: 1.0,
    text: { zh: '在新环境里，我很快就能和陌生人聊起来。', en: 'In new settings, I can strike up conversations with strangers quickly.' } },
  { id: 'q003', setCode: 'quick28', dimension: 'EI', direction: +1, weight: 1.0,
    text: { zh: '我喜欢一边说一边想，说出来思路才更清晰。', en: 'I think out loud — ideas become clearer when I talk them through.' } },
  { id: 'q004', setCode: 'quick28', dimension: 'EI', direction: +1, weight: 1.0,
    text: { zh: '参加聚会时人越多，我反而越兴奋。', en: 'The more people at a gathering, the more energized I feel.' } },
  { id: 'q005', setCode: 'quick28', dimension: 'EI', direction: +1, weight: 1.0,
    text: { zh: '我喜欢在开放工位上工作，太安静的办公室会让我犯困。', en: 'I enjoy working in open shared spaces; overly quiet offices make me drowsy.' } },
  { id: 'q006', setCode: 'quick28', dimension: 'EI', direction: -1, weight: 1.0,
    text: { zh: '在热闹的聚会之后，我需要独处一段时间充电。', en: 'I need solo time to recharge after a lively gathering.' } },
  { id: 'q007', setCode: 'quick28', dimension: 'EI', direction: -1, weight: 1.0,
    text: { zh: '比起群聊，我更喜欢和一两个人深入聊。', en: 'I prefer deep one-on-one conversation over large group chats.' } },

  /* ============= quick28：SN（7 题，5 正 2 反） ============= */
  { id: 'q008', setCode: 'quick28', dimension: 'SN', direction: +1, weight: 1.0,
    text: { zh: '我喜欢琢磨"如果……会怎样"这种假设。', en: "I enjoy mulling over 'what if' scenarios." } },
  { id: 'q009', setCode: 'quick28', dimension: 'SN', direction: +1, weight: 1.0,
    text: { zh: '别人没注意到的隐喻和象征，我经常会留意到。', en: 'I often pick up on metaphors and symbolism others miss.' } },
  { id: 'q010', setCode: 'quick28', dimension: 'SN', direction: +1, weight: 1.0,
    text: { zh: '看电影或读书，我更在意它背后想表达什么。', en: 'When I watch a film or read a book, the underlying message matters more to me than the plot.' } },
  { id: 'q011', setCode: 'quick28', dimension: 'SN', direction: +1, weight: 1.0,
    text: { zh: '我经常突然冒出一些别人觉得奇怪的灵感。', en: 'Unusual ideas pop into my head out of nowhere.' } },
  { id: 'q012', setCode: 'quick28', dimension: 'SN', direction: +1, weight: 1.0,
    text: { zh: '比起按部就班，我更愿意探索新方法。', en: "I'd rather explore new approaches than follow established procedures." } },
  { id: 'q013', setCode: 'quick28', dimension: 'SN', direction: -1, weight: 1.0,
    text: { zh: '比起空泛的理论，我更相信亲眼看到的事实。', en: 'I trust what I can see and verify over abstract theories.' } },
  { id: 'q014', setCode: 'quick28', dimension: 'SN', direction: -1, weight: 1.0,
    text: { zh: '学新东西时，我更喜欢具体步骤而不是宏观概念。', en: 'I learn better through concrete steps than through abstract concepts.' } },

  /* ============= quick28：TF（7 题，5 正 2 反） ============= */
  { id: 'q015', setCode: 'quick28', dimension: 'TF', direction: +1, weight: 1.0,
    text: { zh: '做决定时，我看重逻辑是否站得住脚，而不是大家心里舒不舒服。', en: 'When deciding, I focus on whether the logic holds up, not whether everyone feels comfortable.' } },
  { id: 'q016', setCode: 'quick28', dimension: 'TF', direction: +1, weight: 1.0,
    text: { zh: '被批评时，我更想知道对方的论据，而不是对方的语气。', en: 'When criticized, I focus on the argument, not the tone.' } },
  { id: 'q017', setCode: 'quick28', dimension: 'TF', direction: +1, weight: 1.0,
    text: { zh: '工作里，我能直接指出同事方案的漏洞。', en: "I'm comfortable pointing out flaws in a colleague's proposal directly." } },
  { id: 'q018', setCode: 'quick28', dimension: 'TF', direction: +1, weight: 1.0,
    text: { zh: '比起被喜欢，我更在意被尊重。', en: "I'd rather be respected than liked." } },
  { id: 'q019', setCode: 'quick28', dimension: 'TF', direction: +1, weight: 1.0,
    text: { zh: '看到不公平的事，我会先分析原因，而不是先共情受害者。', en: 'When something unfair happens, I analyze the cause before empathizing with the person hurt.' } },
  { id: 'q020', setCode: 'quick28', dimension: 'TF', direction: -1, weight: 1.0,
    text: { zh: '朋友难过时，我会先安慰他，分析问题可以等。', en: 'When a friend is upset I comfort them first — the problem-solving can wait.' } },
  { id: 'q021', setCode: 'quick28', dimension: 'TF', direction: -1, weight: 1.0,
    text: { zh: '做选择前，我会想想我的决定会让谁难受。', en: "Before deciding, I think about whose feelings my choice might affect." } },

  /* ============= quick28：JP（7 题，5 正 2 反） ============= */
  { id: 'q022', setCode: 'quick28', dimension: 'JP', direction: +1, weight: 1.0,
    text: { zh: '我喜欢留着多种可能，不急着下决定。', en: 'I like to keep multiple options open without rushing a decision.' } },
  { id: 'q023', setCode: 'quick28', dimension: 'JP', direction: +1, weight: 1.0,
    text: { zh: '临近 deadline 时我的灵感反而最爆发。', en: 'I do my best work right before a deadline.' } },
  { id: 'q024', setCode: 'quick28', dimension: 'JP', direction: +1, weight: 1.0,
    text: { zh: '旅行不做详细攻略也没关系，走到哪算哪。', en: "I'm fine traveling without a detailed plan — I figure it out as I go." } },
  { id: 'q025', setCode: 'quick28', dimension: 'JP', direction: +1, weight: 1.0,
    text: { zh: '计划写得太死，我反而不想执行了。', en: 'A plan that feels too rigid actually makes me less likely to follow it.' } },
  { id: 'q026', setCode: 'quick28', dimension: 'JP', direction: +1, weight: 1.0,
    text: { zh: '半路看到更有意思的事，我经常临时改变路线。', en: "I often change my route mid-way when something more interesting catches my eye." } },
  { id: 'q027', setCode: 'quick28', dimension: 'JP', direction: -1, weight: 1.0,
    text: { zh: '没有清单或日程，我就会有点焦虑。', en: 'I get anxious without a checklist or schedule.' } },
  { id: 'q028', setCode: 'quick28', dimension: 'JP', direction: -1, weight: 1.0,
    text: { zh: '我习惯提前几天把要做的事都安排好。', en: 'I plan out my tasks several days in advance.' } },

  /* ============= standard93：EI（21 题，15 正 6 反） ============= */
  { id: 'q029', setCode: 'standard93', dimension: 'EI', direction: +1, weight: 1.0,
    text: { zh: '我喜欢成为聚会里的中心人物。', en: 'I enjoy being the center of attention at gatherings.' } },
  { id: 'q030', setCode: 'standard93', dimension: 'EI', direction: +1, weight: 1.0,
    text: { zh: '第一次见面的人我也能聊得很自然。', en: 'I can converse naturally with someone I just met.' } },
  { id: 'q031', setCode: 'standard93', dimension: 'EI', direction: +1, weight: 1.0,
    text: { zh: '我经常主动跟陌生人搭话。', en: 'I often start conversations with strangers.' } },
  { id: 'q032', setCode: 'standard93', dimension: 'EI', direction: +1, weight: 1.0,
    text: { zh: '团队讨论中，我通常是先开口的那一个。', en: 'In group discussions, I tend to be the first to speak.' } },
  { id: 'q033', setCode: 'standard93', dimension: 'EI', direction: +1, weight: 1.0,
    text: { zh: '处理事情时，我宁愿打电话也不愿发消息。', en: 'When handling something, I prefer a phone call over messaging.' } },
  { id: 'q034', setCode: 'standard93', dimension: 'EI', direction: +1, weight: 1.0,
    text: { zh: '一周不出门见朋友，我会觉得难受。', en: 'A week without seeing friends in person leaves me restless.' } },
  { id: 'q035', setCode: 'standard93', dimension: 'EI', direction: +1, weight: 1.0,
    text: { zh: '我喜欢一次性认识很多新朋友。', en: 'I enjoy meeting many new people at once.' } },
  { id: 'q036', setCode: 'standard93', dimension: 'EI', direction: +1, weight: 1.0,
    text: { zh: '我会主动在公司茶水间跟同事闲聊。', en: 'I willingly chat with coworkers in the break room.' } },
  { id: 'q037', setCode: 'standard93', dimension: 'EI', direction: +1, weight: 1.0,
    text: { zh: '旅行最大的乐趣对我来说是认识当地人。', en: 'For me, the best part of travel is meeting locals.' } },
  { id: 'q038', setCode: 'standard93', dimension: 'EI', direction: +1, weight: 1.0,
    text: { zh: '在聚会上我能在不同小圈子之间自如穿梭。', en: 'At parties I move easily between different cliques.' } },
  { id: 'q039', setCode: 'standard93', dimension: 'EI', direction: +1, weight: 1.0,
    text: { zh: '一桌人都不说话时，我会忍不住打破沉默。', en: 'When a table goes silent I find myself breaking the quiet.' } },
  { id: 'q040', setCode: 'standard93', dimension: 'EI', direction: +1, weight: 1.0,
    text: { zh: '我经常被人形容成"自来熟"。', en: "People often describe me as 'instantly warm with strangers'." } },
  { id: 'q041', setCode: 'standard93', dimension: 'EI', direction: +1, weight: 1.0,
    text: { zh: '周末我宁愿出门也不愿宅在家。', en: "On weekends I'd rather go out than stay home." } },
  { id: 'q042', setCode: 'standard93', dimension: 'EI', direction: +1, weight: 1.0,
    text: { zh: '群聊、弹幕这类场合我都很活跃。', en: "I'm an active participant in group chats and live-stream chats." } },
  { id: 'q043', setCode: 'standard93', dimension: 'EI', direction: +1, weight: 1.0,
    text: { zh: '接到陌生电话时我会有点好奇，想知道是谁。', en: "An unknown call sparks my curiosity rather than dread." } },
  { id: 'q044', setCode: 'standard93', dimension: 'EI', direction: -1, weight: 1.0,
    text: { zh: '和很多人相处一整天后，我会感到精疲力尽。', en: 'A whole day surrounded by people leaves me drained.' } },
  { id: 'q045', setCode: 'standard93', dimension: 'EI', direction: -1, weight: 1.0,
    text: { zh: '我宁愿在咖啡馆角落看书，也不愿坐在窗边。', en: "I'd rather read in the corner of a café than sit by the window." } },
  { id: 'q046', setCode: 'standard93', dimension: 'EI', direction: -1, weight: 1.0,
    text: { zh: '我习惯把一句话在脑子里想清楚再说出来。', en: 'I run sentences through my head before I say them.' } },
  { id: 'q047', setCode: 'standard93', dimension: 'EI', direction: -1, weight: 1.0,
    text: { zh: '有几个真正了解我的朋友就够了。', en: 'A few friends who really get me is plenty.' } },
  { id: 'q048', setCode: 'standard93', dimension: 'EI', direction: -1, weight: 1.0,
    text: { zh: '长时间的群体活动让我想找个角落歇一会儿。', en: 'After long group activities I want to find a corner and decompress.' } },
  { id: 'q049', setCode: 'standard93', dimension: 'EI', direction: -1, weight: 1.0,
    text: { zh: '我不喜欢被强行点名发言。', en: 'I dislike being put on the spot to speak.' } },

  /* ============= standard93：SN（26 题，18 正 8 反） ============= */
  { id: 'q050', setCode: 'standard93', dimension: 'SN', direction: +1, weight: 1.0,
    text: { zh: '我经常被自己的奇怪想法逗笑。', en: 'My own strange thoughts often crack me up.' } },
  { id: 'q051', setCode: 'standard93', dimension: 'SN', direction: +1, weight: 1.0,
    text: { zh: '比起记住人脸，我更容易记住别人说过的金句。', en: "I remember people's striking phrases more easily than their faces." } },
  { id: 'q052', setCode: 'standard93', dimension: 'SN', direction: +1, weight: 1.0,
    text: { zh: '我喜欢琢磨事情背后的"为什么"。', en: "I enjoy digging into the 'why' behind things." } },
  { id: 'q053', setCode: 'standard93', dimension: 'SN', direction: +1, weight: 1.0,
    text: { zh: '我容易被科幻小说和未来话题吸引。', en: "Sci-fi and futurism easily pull me in." } },
  { id: 'q054', setCode: 'standard93', dimension: 'SN', direction: +1, weight: 1.0,
    text: { zh: '我习惯把一件小事联想到更大的格局。', en: 'I tend to connect a small event to a much bigger picture.' } },
  { id: 'q055', setCode: 'standard93', dimension: 'SN', direction: +1, weight: 1.0,
    text: { zh: '别人话还没说完，我经常已经猜到后半段。', en: "I often guess the second half of what someone's about to say." } },
  { id: 'q056', setCode: 'standard93', dimension: 'SN', direction: +1, weight: 1.0,
    text: { zh: '我喜欢把不同领域的东西做类比。', en: 'I love drawing analogies between unrelated fields.' } },
  { id: 'q057', setCode: 'standard93', dimension: 'SN', direction: +1, weight: 1.0,
    text: { zh: '"时间为什么存在"这种问题让我兴奋。', en: "Questions like 'why does time exist' genuinely excite me." } },
  { id: 'q058', setCode: 'standard93', dimension: 'SN', direction: +1, weight: 1.0,
    text: { zh: '我做决定常常先靠直觉，事后再补论据。', en: 'I usually decide on instinct first, then justify it afterwards.' } },
  { id: 'q059', setCode: 'standard93', dimension: 'SN', direction: +1, weight: 1.0,
    text: { zh: '我经常一边做事一边走神到完全不相关的话题。', en: 'My mind frequently wanders mid-task to something totally unrelated.' } },
  { id: 'q060', setCode: 'standard93', dimension: 'SN', direction: +1, weight: 1.0,
    text: { zh: '看新闻我喜欢分析背后的趋势，而不只是看事件。', en: 'I read news for the underlying trends, not just the events.' } },
  { id: 'q061', setCode: 'standard93', dimension: 'SN', direction: +1, weight: 1.0,
    text: { zh: '我喜欢同时进行几个想法或项目，它们能相互启发。', en: 'I like juggling several ideas or projects at once — they cross-pollinate.' } },
  { id: 'q062', setCode: 'standard93', dimension: 'SN', direction: +1, weight: 1.0,
    text: { zh: '我对未被验证的可能性比已被验证的事实更感兴趣。', en: 'Unverified possibilities interest me more than well-established facts.' } },
  { id: 'q063', setCode: 'standard93', dimension: 'SN', direction: +1, weight: 1.0,
    text: { zh: '别人讲事实时，我下意识就想问"那意味着什么"。', en: "When someone states a fact, I instinctively ask 'what does that mean'." } },
  { id: 'q064', setCode: 'standard93', dimension: 'SN', direction: +1, weight: 1.0,
    text: { zh: '我喜欢看抽象画或结构复杂的音乐。', en: 'I enjoy abstract art and structurally complex music.' } },
  { id: 'q065', setCode: 'standard93', dimension: 'SN', direction: +1, weight: 1.0,
    text: { zh: '我经常洗澡时冒出新点子。', en: 'New ideas often hit me in the shower.' } },
  { id: 'q066', setCode: 'standard93', dimension: 'SN', direction: +1, weight: 1.0,
    text: { zh: '我相信人是可以改变的。', en: 'I believe people are genuinely capable of change.' } },
  { id: 'q067', setCode: 'standard93', dimension: 'SN', direction: +1, weight: 1.0,
    text: { zh: '假设题和思想实验都让我有兴趣。', en: 'Hypotheticals and thought experiments fascinate me.' } },
  { id: 'q068', setCode: 'standard93', dimension: 'SN', direction: -1, weight: 1.0,
    text: { zh: '别人讲故事时，越具体的细节我越觉得有意思。', en: "When people tell stories, the more concrete the details the better." } },
  { id: 'q069', setCode: 'standard93', dimension: 'SN', direction: -1, weight: 1.0,
    text: { zh: '我做事更相信经验，不太相信新理论。', en: 'I trust experience over new theories when getting things done.' } },
  { id: 'q070', setCode: 'standard93', dimension: 'SN', direction: -1, weight: 1.0,
    text: { zh: '没亲眼看见的事，我倾向于先打个问号。', en: "If I haven't seen it myself, I treat it as unconfirmed." } },
  { id: 'q071', setCode: 'standard93', dimension: 'SN', direction: -1, weight: 1.0,
    text: { zh: '比起头脑风暴，我更喜欢把已有的方案做精。', en: 'I prefer polishing an existing plan over brainstorming new ones.' } },
  { id: 'q072', setCode: 'standard93', dimension: 'SN', direction: -1, weight: 1.0,
    text: { zh: '电影台词、菜单细节这种事我记得很清楚。', en: 'I remember movie lines and menu details precisely.' } },
  { id: 'q073', setCode: 'standard93', dimension: 'SN', direction: -1, weight: 1.0,
    text: { zh: '我更愿意做一件能立刻看到结果的事。', en: 'I prefer tasks where results show up quickly.' } },
  { id: 'q074', setCode: 'standard93', dimension: 'SN', direction: -1, weight: 1.0,
    text: { zh: '"概念" "理论" "模型"这种词让我有点反感。', en: "Words like 'concept' or 'model' make me slightly impatient." } },
  { id: 'q075', setCode: 'standard93', dimension: 'SN', direction: -1, weight: 1.0,
    text: { zh: '我更喜欢用过去验证过有效的方法。', en: "I prefer methods that have already proven they work." } },

  /* ============= standard93：TF（24 题，16 正 8 反） ============= */
  { id: 'q076', setCode: 'standard93', dimension: 'TF', direction: +1, weight: 1.0,
    text: { zh: '听到一个观点，我会先判断它前后是否一致。', en: 'When I hear an argument I first check whether it holds together internally.' } },
  { id: 'q077', setCode: 'standard93', dimension: 'TF', direction: +1, weight: 1.0,
    text: { zh: '我能在情绪里跳出来分析自己。', en: 'I can step outside my emotions and analyze myself.' } },
  { id: 'q078', setCode: 'standard93', dimension: 'TF', direction: +1, weight: 1.0,
    text: { zh: '我经常觉得身边人过于情绪化。', en: 'I often find people around me overly emotional.' } },
  { id: 'q079', setCode: 'standard93', dimension: 'TF', direction: +1, weight: 1.0,
    text: { zh: '做决定时，"会让谁失望"这件事不会左右我太多。', en: "'Who will be disappointed' doesn't sway my decisions much." } },
  { id: 'q080', setCode: 'standard93', dimension: 'TF', direction: +1, weight: 1.0,
    text: { zh: '我习惯先把事实讲清楚，再考虑对方的感受。', en: "I usually lay out the facts first and consider feelings second." } },
  { id: 'q081', setCode: 'standard93', dimension: 'TF', direction: +1, weight: 1.0,
    text: { zh: '我看重结果是否正确，而不是过程舒不舒服。', en: 'I care more about the outcome being right than the process being comfortable.' } },
  { id: 'q082', setCode: 'standard93', dimension: 'TF', direction: +1, weight: 1.0,
    text: { zh: '我能很冷静地讨论敏感话题。', en: 'I can discuss sensitive topics calmly.' } },
  { id: 'q083', setCode: 'standard93', dimension: 'TF', direction: +1, weight: 1.0,
    text: { zh: '我经常质疑权威给出的说法。', en: 'I often question what authorities say.' } },
  { id: 'q084', setCode: 'standard93', dimension: 'TF', direction: +1, weight: 1.0,
    text: { zh: '我更在意论据本身，而不是讲论据的人。', en: 'The argument itself matters to me more than who is making it.' } },
  { id: 'q085', setCode: 'standard93', dimension: 'TF', direction: +1, weight: 1.0,
    text: { zh: '在工作中我能分得清友情和合作。', en: 'At work I can separate friendship from collaboration.' } },
  { id: 'q086', setCode: 'standard93', dimension: 'TF', direction: +1, weight: 1.0,
    text: { zh: '我不容易被别人的情绪绑架。', en: "I'm not easily swayed by other people's emotions." } },
  { id: 'q087', setCode: 'standard93', dimension: 'TF', direction: +1, weight: 1.0,
    text: { zh: '我喜欢清楚的规则，模糊的规则让我难受。', en: 'I prefer clear rules; vague ones bother me.' } },
  { id: 'q088', setCode: 'standard93', dimension: 'TF', direction: +1, weight: 1.0,
    text: { zh: '为了大局，我能接受做出残酷的决定。', en: "For the greater good, I can make harsh decisions." } },
  { id: 'q089', setCode: 'standard93', dimension: 'TF', direction: +1, weight: 1.0,
    text: { zh: '"双方各让一步"的和稀泥方案让我不满意。', en: "Splitting-the-difference compromises tend to dissatisfy me." } },
  { id: 'q090', setCode: 'standard93', dimension: 'TF', direction: +1, weight: 1.0,
    text: { zh: '我对一个人的能力比对他的人品更敏感。', en: "I notice someone's competence before their warmth." } },
  { id: 'q091', setCode: 'standard93', dimension: 'TF', direction: +1, weight: 1.0,
    text: { zh: '数据比故事更有说服力。', en: 'Data persuades me more than stories.' } },
  { id: 'q092', setCode: 'standard93', dimension: 'TF', direction: -1, weight: 1.0,
    text: { zh: '我容易被电影或新闻里的故事打动。', en: 'Stories from films or the news easily move me.' } },
  { id: 'q093', setCode: 'standard93', dimension: 'TF', direction: -1, weight: 1.0,
    text: { zh: '朋友的难过会让我也跟着低落好一阵。', en: "A friend's sadness lingers with me for a while." } },
  { id: 'q094', setCode: 'standard93', dimension: 'TF', direction: -1, weight: 1.0,
    text: { zh: '我倾向于让大家都开心，哪怕自己委屈一点。', en: "I'd rather everyone be happy, even at my own expense." } },
  { id: 'q095', setCode: 'standard93', dimension: 'TF', direction: -1, weight: 1.0,
    text: { zh: '我会因为别人一句话琢磨好久。', en: "A single remark can keep me thinking for a long time." } },
  { id: 'q096', setCode: 'standard93', dimension: 'TF', direction: -1, weight: 1.0,
    text: { zh: '我相信价值观比逻辑更重要。', en: 'I believe values matter more than logic.' } },
  { id: 'q097', setCode: 'standard93', dimension: 'TF', direction: -1, weight: 1.0,
    text: { zh: '看到流浪动物，我会忍不住停下来。', en: "I can't help stopping for stray animals." } },
  { id: 'q098', setCode: 'standard93', dimension: 'TF', direction: -1, weight: 1.0,
    text: { zh: '我更愿意先听完对方的感受，再讲我的观点。', en: "I'd rather hear someone's feelings out first, then share my view." } },
  { id: 'q099', setCode: 'standard93', dimension: 'TF', direction: -1, weight: 1.0,
    text: { zh: '光听语气我就能猜出对方今天心情。', en: "I can tell someone's mood from their tone alone." } },

  /* ============= standard93：JP（22 题，15 正 7 反） ============= */
  { id: 'q100', setCode: 'standard93', dimension: 'JP', direction: +1, weight: 1.0,
    text: { zh: '我手机里同时有好几个项目，没一个真正完结。', en: 'I have multiple unfinished projects on my phone simultaneously.' } },
  { id: 'q101', setCode: 'standard93', dimension: 'JP', direction: +1, weight: 1.0,
    text: { zh: '我的玩法是"先开始再说"。', en: "My approach is 'just start, figure out the rest later'." } },
  { id: 'q102', setCode: 'standard93', dimension: 'JP', direction: +1, weight: 1.0,
    text: { zh: '计划被打乱时我也能很快适应。', en: 'I adapt quickly when plans get derailed.' } },
  { id: 'q103', setCode: 'standard93', dimension: 'JP', direction: +1, weight: 1.0,
    text: { zh: '一件事做到一半，我经常被新点子吸引去做另一件。', en: 'I often abandon something mid-way when a new idea grabs me.' } },
  { id: 'q104', setCode: 'standard93', dimension: 'JP', direction: +1, weight: 1.0,
    text: { zh: '我相信"事到临头总会有办法"。', en: "I trust that 'when push comes to shove, there's always a way'." } },
  { id: 'q105', setCode: 'standard93', dimension: 'JP', direction: +1, weight: 1.0,
    text: { zh: '旅行临时改行程对我是常态。', en: 'Changing my travel itinerary on the fly is the norm for me.' } },
  { id: 'q106', setCode: 'standard93', dimension: 'JP', direction: +1, weight: 1.0,
    text: { zh: '做事时我更享受探索过程，而不是直奔结果。', en: 'I enjoy the exploring more than rushing toward the result.' } },
  { id: 'q107', setCode: 'standard93', dimension: 'JP', direction: +1, weight: 1.0,
    text: { zh: '购物时我喜欢逛着挑，不爱按清单买。', en: 'Shopping, I like to browse rather than work from a list.' } },
  { id: 'q108', setCode: 'standard93', dimension: 'JP', direction: +1, weight: 1.0,
    text: { zh: '周末怎么过我经常临到周五才决定。', en: "I often only decide weekend plans by Friday." } },
  { id: 'q109', setCode: 'standard93', dimension: 'JP', direction: +1, weight: 1.0,
    text: { zh: '死板的时间表让我抵触。', en: 'Rigid schedules make me resistant.' } },
  { id: 'q110', setCode: 'standard93', dimension: 'JP', direction: +1, weight: 1.0,
    text: { zh: '我浏览器同时开着十几个标签是常事。', en: 'Having dozens of browser tabs open is normal for me.' } },
  { id: 'q111', setCode: 'standard93', dimension: 'JP', direction: +1, weight: 1.0,
    text: { zh: '我经常因为路上的小发现而迟到。', en: 'I often run late because something on the way caught my eye.' } },
  { id: 'q112', setCode: 'standard93', dimension: 'JP', direction: +1, weight: 1.0,
    text: { zh: '一件事还有变数时我反而更有兴趣。', en: "I'm more interested in things that still have unknowns." } },
  { id: 'q113', setCode: 'standard93', dimension: 'JP', direction: +1, weight: 1.0,
    text: { zh: '我能在混乱里找到自己的节奏。', en: 'I find my rhythm even amid chaos.' } },
  { id: 'q114', setCode: 'standard93', dimension: 'JP', direction: +1, weight: 1.0,
    text: { zh: '新事物容易吸引我，旧的项目常常半途而废。', en: 'New shiny things pull me away from older projects.' } },
  { id: 'q115', setCode: 'standard93', dimension: 'JP', direction: -1, weight: 1.0,
    text: { zh: '我会提前规划下一周要做什么。', en: 'I plan out next week in advance.' } },
  { id: 'q116', setCode: 'standard93', dimension: 'JP', direction: -1, weight: 1.0,
    text: { zh: '没列清单做事我就没安全感。', en: 'Without a checklist I feel uneasy.' } },
  { id: 'q117', setCode: 'standard93', dimension: 'JP', direction: -1, weight: 1.0,
    text: { zh: '一件事没完成我会睡不踏实。', en: "An unfinished task keeps me from sleeping well." } },
  { id: 'q118', setCode: 'standard93', dimension: 'JP', direction: -1, weight: 1.0,
    text: { zh: '我喜欢把目标拆成阶段、一步步完成。', en: 'I like breaking goals into stages and ticking them off.' } },
  { id: 'q119', setCode: 'standard93', dimension: 'JP', direction: -1, weight: 1.0,
    text: { zh: '我宁愿早到机场等飞机，也不愿赶。', en: "I'd rather wait at the airport than rush there." } },
  { id: 'q120', setCode: 'standard93', dimension: 'JP', direction: -1, weight: 1.0,
    text: { zh: '我经常用日历或表格来管理生活。', en: 'I rely on calendars or spreadsheets to run my life.' } },
  { id: 'q121', setCode: 'standard93', dimension: 'JP', direction: -1, weight: 1.0,
    text: { zh: '决定之后我很少再回头改。', en: 'Once I decide, I rarely revisit it.' } },

  /* ============= pro144 增量：AT（30 题，20 正 10 反） ============= */
  { id: 'q122', setCode: 'pro144', dimension: 'AT', direction: +1, weight: 1.0,
    text: { zh: '做完决定后，我很少再去后悔。', en: 'Once I decide, I rarely regret it.' } },
  { id: 'q123', setCode: 'pro144', dimension: 'AT', direction: +1, weight: 1.0,
    text: { zh: '事情没按计划走，我也能很快释怀。', en: 'When things go off plan, I shake it off fast.' } },
  { id: 'q124', setCode: 'pro144', dimension: 'AT', direction: +1, weight: 1.0,
    text: { zh: '我对自己的能力有比较清晰的判断。', en: 'I have a clear, honest read on my own abilities.' } },
  { id: 'q125', setCode: 'pro144', dimension: 'AT', direction: +1, weight: 1.0,
    text: { zh: '别人的批评不会让我整夜睡不着。', en: "Criticism doesn't keep me up at night." } },
  { id: 'q126', setCode: 'pro144', dimension: 'AT', direction: +1, weight: 1.0,
    text: { zh: '我能接受自己不完美这件事。', en: "I'm at peace with not being perfect." } },
  { id: 'q127', setCode: 'pro144', dimension: 'AT', direction: +1, weight: 1.0,
    text: { zh: '失败一次不会让我整体怀疑自己。', en: "One setback doesn't shake my overall confidence." } },
  { id: 'q128', setCode: 'pro144', dimension: 'AT', direction: +1, weight: 1.0,
    text: { zh: '别人对我礼貌时，我不会过度解读。', en: "I don't over-read other people's polite gestures." } },
  { id: 'q129', setCode: 'pro144', dimension: 'AT', direction: +1, weight: 1.0,
    text: { zh: '我对未来的不确定性不会太焦虑。', en: 'Future uncertainty does not weigh on me.' } },
  { id: 'q130', setCode: 'pro144', dimension: 'AT', direction: +1, weight: 1.0,
    text: { zh: '我能很快从糟糕的反馈里走出来。', en: 'I bounce back from bad feedback quickly.' } },
  { id: 'q131', setCode: 'pro144', dimension: 'AT', direction: +1, weight: 1.0,
    text: { zh: '我不需要外部认可来确认自己的价值。', en: "I don't need external validation to feel worthy." } },
  { id: 'q132', setCode: 'pro144', dimension: 'AT', direction: +1, weight: 1.0,
    text: { zh: '高压情境下我能保持稳定。', en: 'I stay steady under high pressure.' } },
  { id: 'q133', setCode: 'pro144', dimension: 'AT', direction: +1, weight: 1.0,
    text: { zh: '完成后我不会反复检查自己有没有出错。', en: "Once it's done, I don't keep re-checking for mistakes." } },
  { id: 'q134', setCode: 'pro144', dimension: 'AT', direction: +1, weight: 1.0,
    text: { zh: '我能心安理得地说"这就够好了"。', en: "I can confidently say 'this is good enough'." } },
  { id: 'q135', setCode: 'pro144', dimension: 'AT', direction: +1, weight: 1.0,
    text: { zh: '同辈竞争不太影响我的心情。', en: "Peer competition doesn't move my mood much." } },
  { id: 'q136', setCode: 'pro144', dimension: 'AT', direction: +1, weight: 1.0,
    text: { zh: '别人的成功不会让我觉得自己不够好。', en: "Other people's wins don't make me feel inadequate." } },
  { id: 'q137', setCode: 'pro144', dimension: 'AT', direction: +1, weight: 1.0,
    text: { zh: '我接受自己不必随时保持积极情绪。', en: "I'm okay with not feeling upbeat all the time." } },
  { id: 'q138', setCode: 'pro144', dimension: 'AT', direction: +1, weight: 1.0,
    text: { zh: '我能区分"自己的看法"和"别人对我的看法"。', en: "I can tell apart 'my view of me' from 'others' view of me'." } },
  { id: 'q139', setCode: 'pro144', dimension: 'AT', direction: +1, weight: 1.0,
    text: { zh: '面对大事我能保持冷静。', en: 'I keep my cool in high-stakes moments.' } },
  { id: 'q140', setCode: 'pro144', dimension: 'AT', direction: +1, weight: 1.0,
    text: { zh: '选完之后我很少琢磨"早知道选另一个"。', en: "After choosing, I rarely second-guess 'I should've picked the other'." } },
  { id: 'q141', setCode: 'pro144', dimension: 'AT', direction: +1, weight: 1.0,
    text: { zh: '我不太把别人不经意的话往心里去。', en: "I don't take casual remarks to heart." } },
  { id: 'q142', setCode: 'pro144', dimension: 'AT', direction: -1, weight: 1.0,
    text: { zh: '我脑子里经常回放刚才那段对话哪句没说好。', en: "I replay conversations in my head and pick out what I should've said better." } },
  { id: 'q143', setCode: 'pro144', dimension: 'AT', direction: -1, weight: 1.0,
    text: { zh: '做完事后我会反复检查有没有出错。', en: 'After finishing, I re-check for mistakes again and again.' } },
  { id: 'q144', setCode: 'pro144', dimension: 'AT', direction: -1, weight: 1.0,
    text: { zh: '别人的一个表情我能琢磨半天。', en: "I can dwell on a single facial expression for a long time." } },
  { id: 'q145', setCode: 'pro144', dimension: 'AT', direction: -1, weight: 1.0,
    text: { zh: '我担心自己不够好，所以一直推自己更好。', en: 'I worry about not being good enough, so I keep pushing myself.' } },
  { id: 'q146', setCode: 'pro144', dimension: 'AT', direction: -1, weight: 1.0,
    text: { zh: '决定前后我都会反复权衡。', en: 'I weigh options endlessly, before and after deciding.' } },
  { id: 'q147', setCode: 'pro144', dimension: 'AT', direction: -1, weight: 1.0,
    text: { zh: '我对自己的要求经常比对别人的要求更高。', en: 'I hold myself to higher standards than I hold others.' } },
  { id: 'q148', setCode: 'pro144', dimension: 'AT', direction: -1, weight: 1.0,
    text: { zh: '收到批评后我会失眠。', en: 'Criticism can cost me a night of sleep.' } },
  { id: 'q149', setCode: 'pro144', dimension: 'AT', direction: -1, weight: 1.0,
    text: { zh: '我经常觉得"我本应该做得更好"。', en: "I often feel 'I should have done better'." } },
  { id: 'q150', setCode: 'pro144', dimension: 'AT', direction: -1, weight: 1.0,
    text: { zh: '我容易被身边人的情绪影响。', en: "Other people's emotions easily rub off on me." } },
  { id: 'q151', setCode: 'pro144', dimension: 'AT', direction: -1, weight: 1.0,
    text: { zh: '即使做得不错，我也会担心下次掉链子。', en: "Even after a win, I worry about messing up next time." } },

  /* ============= pro144 增量：深度补充（21 题） ============= */
  /* EI 补充 5 题 */
  { id: 'q152', setCode: 'pro144', dimension: 'EI', direction: +1, weight: 1.0,
    text: { zh: '我喜欢线下面对面沟通胜过线上文字沟通。', en: 'I prefer face-to-face conversation over messaging.' } },
  { id: 'q153', setCode: 'pro144', dimension: 'EI', direction: +1, weight: 1.0,
    text: { zh: '周末没活动时我会主动想办法约人。', en: "When a weekend is empty, I find people to hang out with." } },
  { id: 'q154', setCode: 'pro144', dimension: 'EI', direction: +1, weight: 1.0,
    text: { zh: '一个人旅行对我来说不太有吸引力。', en: 'Solo travel does not particularly appeal to me.' } },
  { id: 'q155', setCode: 'pro144', dimension: 'EI', direction: -1, weight: 1.0,
    text: { zh: '一个安静的下午、一本书，我会觉得很满足。', en: 'A quiet afternoon and a book leave me content.' } },
  { id: 'q156', setCode: 'pro144', dimension: 'EI', direction: -1, weight: 1.0,
    text: { zh: '我更喜欢在熟悉的小圈子里待着。', en: 'I prefer hanging in a small familiar circle.' } },

  /* SN 补充 5 题 */
  { id: 'q157', setCode: 'pro144', dimension: 'SN', direction: +1, weight: 1.0,
    text: { zh: '一件小事我能推演出很多种可能。', en: 'From one small event I can imagine many possible outcomes.' } },
  { id: 'q158', setCode: 'pro144', dimension: 'SN', direction: +1, weight: 1.0,
    text: { zh: '还没发生的事我会想很久。', en: "I dwell on things that haven't happened yet." } },
  { id: 'q159', setCode: 'pro144', dimension: 'SN', direction: +1, weight: 1.0,
    text: { zh: '假设性的脑洞讨论我能聊很久。', en: 'I can talk for hours about purely hypothetical scenarios.' } },
  { id: 'q160', setCode: 'pro144', dimension: 'SN', direction: -1, weight: 1.0,
    text: { zh: '做项目时我偏好用过去验证过的流程。', en: 'For projects I lean on proven workflows.' } },
  { id: 'q161', setCode: 'pro144', dimension: 'SN', direction: -1, weight: 1.0,
    text: { zh: '比起抽象概念，我更喜欢具体可触摸的事物。', en: 'I prefer tangible things over abstract concepts.' } },

  /* TF 补充 6 题 */
  { id: 'q162', setCode: 'pro144', dimension: 'TF', direction: +1, weight: 1.0,
    text: { zh: '同事工作没做好，我能直接指出来。', en: "When a colleague drops the ball, I'll say so directly." } },
  { id: 'q163', setCode: 'pro144', dimension: 'TF', direction: +1, weight: 1.0,
    text: { zh: '朋友找我帮忙如果不合理，我能开口说不。', en: "I can decline a friend's unreasonable favor." } },
  { id: 'q164', setCode: 'pro144', dimension: 'TF', direction: +1, weight: 1.0,
    text: { zh: '我更愿意用逻辑说服别人，而不是情感打动。', en: 'I rely on logic to persuade, not on emotional appeal.' } },
  { id: 'q165', setCode: 'pro144', dimension: 'TF', direction: +1, weight: 1.0,
    text: { zh: '我习惯用利弊清单来做决定。', en: 'I use pros-and-cons lists to decide.' } },
  { id: 'q166', setCode: 'pro144', dimension: 'TF', direction: -1, weight: 1.0,
    text: { zh: '朋友闹矛盾时，我会先听他们各自的情绪。', en: "When friends fight, I listen to each one's feelings first." } },
  { id: 'q167', setCode: 'pro144', dimension: 'TF', direction: -1, weight: 1.0,
    text: { zh: '决定后我会想这件事会对身边人造成什么影响。', en: 'After deciding, I think about how it affects the people around me.' } },

  /* JP 补充 5 题 */
  { id: 'q168', setCode: 'pro144', dimension: 'JP', direction: +1, weight: 1.0,
    text: { zh: '我喜欢"半成品式"地推进事情。', en: "I like pushing things forward in a 'half-finished' style." } },
  { id: 'q169', setCode: 'pro144', dimension: 'JP', direction: +1, weight: 1.0,
    text: { zh: '我喜欢留充裕的时间给临时灵感。', en: 'I prefer leaving room for spontaneous ideas.' } },
  { id: 'q170', setCode: 'pro144', dimension: 'JP', direction: +1, weight: 1.0,
    text: { zh: '我喜欢边走边想方向。', en: 'I figure out the direction as I go.' } },
  { id: 'q171', setCode: 'pro144', dimension: 'JP', direction: -1, weight: 1.0,
    text: { zh: '我喜欢一开始就把目标和时间钉死。', en: 'I like nailing down the goal and timeline up-front.' } },
  { id: 'q172', setCode: 'pro144', dimension: 'JP', direction: -1, weight: 1.0,
    text: { zh: '做事我尽量留 buffer，不喜欢踩点。', en: "I leave buffer time; I dislike cutting it close." } },
];

/**
 * 暴露到全局：
 *   - quick28      : 仅 setCode === 'quick28'
 *   - standard93   : 仅 setCode === 'standard93'
 *   - pro144       : standard93 + setCode === 'pro144'  (即 93 + 51 = 144)
 */
window.QUESTIONS = {
  quick28: _QUESTIONS_FLAT.filter(q => q.setCode === 'quick28'),
  standard93: _QUESTIONS_FLAT.filter(q => q.setCode === 'standard93'),
  pro144: _QUESTIONS_FLAT.filter(q => q.setCode === 'standard93' || q.setCode === 'pro144'),
};

// 自检：在控制台打印题量分布，便于开发期验证
if (typeof console !== 'undefined') {
  console.log('[questions.js] quick28 =', window.QUESTIONS.quick28.length,
              '| standard93 =', window.QUESTIONS.standard93.length,
              '| pro144 =', window.QUESTIONS.pro144.length);
}
